-- Run only if you do not use `php artisan migrate --seed`.
ALTER TABLE users ADD role VARCHAR2(10) DEFAULT 'user' NOT NULL;

CREATE TABLE menu_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_id VARCHAR2(20) NOT NULL UNIQUE,
  name VARCHAR2(255) NOT NULL,
  image VARCHAR2(255),
  category VARCHAR2(100),
  area VARCHAR2(100),
  instructions CLOB,
  ingredients CLOB NOT NULL,
  price NUMBER(8,2) NOT NULL,
  status VARCHAR2(10) DEFAULT 'ada' NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
